### ISSUE TITLE
housing units API returning deleted units 

### ISSUE THREAD

**Issue by suryayadavalli** [hserv/coordinated-entry#126]
Reported by @przemyslaw  on 08/24 that HOME APP is seeing housing units that are in deleted state.

**Comment by suryayadavalli** [comment]
Fixed with commit https://github.com/hserv/coordinated-entry/commit/32ec57a3e9a67afa0e5f612768abc4ca2e971511
Resolved, deployed in production

**Comment by eric-jahn** [comment]
From @pgorecki "@surya.yadavalli housing units works as expected although I can still see `deleted` field in the request (it's not a problem)".  Once the deleted field is removed, let's close this.

**Comment by eric-jahn** [comment]
@suryayadavalli reported this is completed and deployed.
