### ISSUE TITLE
New redirect URLs for HOME APP

### ISSUE THREAD

**Issue by suryayadavalli** [hserv/coordinated-entry#173]
- https://new.mosbehome.ctagroup.org/_oauth/HMIS%3fclose
- https://old.mosbehome.ctagroup.org/_oauth/HMIS%3fclose

**Comment by suryayadavalli** [comment]
This is resolved now.

**Comment by eric-jahn** [comment]
@suryayadavalli : from @CTAJavier "@surya.yadavalli we are still getting this:
`An error occurred Redirect uri https://new.mosbehome.ctagroup.org/_oauth/HMIS%3fclose is not registered`
 can you add that as well ?"

**Comment by suryayadavalli** [comment]
Resolved
